services:
  - type: web
    name: wildlife-project
    runtime: image
    repo: https://github.com/AhmadAlanad/wildlife-project.git
    plan: free
    dockerCommand: php -S 0.0.0.0:10000
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.gdfymhqmlwenvyncqktt:b_tUyAvk5-*,pca@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require